apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      labels:
        app: survey
    spec:
      containers:
        - name: survey
          image: jhansisneha/swe645-hw3:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://surveydb.cslzkqywwmbl.us-east-1.rds.amazonaws.com:3306/surveydb
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin2025
